// The analytics guide: what every number means and exactly how it is calculated (mirrors backend/analytics.py).
// `id`s are linked from panels (Panel help="…") and KPI cards.

export const GUIDE = [
  {
    id: 'data', title: 'Where the data comes from',
    intro: 'Everything here is counted on the server from the full history — every page view, contact, registration and sale since tracking began on 21 Feb 2026. Nothing is sampled.',
    entries: [
      { id: 'tracking', term: 'The tracking script', what: 'A small script on each of our pages (drshumardworkshop.com, joinnow.live, the webinar pages…) records a page view every time a page loads, with the page address, the page it came from, the ad / UTM details in the link, and the browser.' },
      { id: 'visitor-id', term: 'How a visitor is recognised', what: 'The first time a browser loads one of our pages it is given a random ID, stored in that browser for that website. Every later page view from the same browser on the same site carries the same ID.',
        note: 'The same person on their phone and their laptop — or on two different domains — starts out as two visitors. When they give their email on both, the records are merged into one person automatically, and their page views move with them.' },
      { id: 'identification', term: 'How a visitor becomes a lead', what: 'When someone types their email or phone into a form we track (opt-in, registration), their visitor record gains that email/phone. From then on they are an identified lead.' },
      { id: 'registration-source', term: 'Registrations and tags', what: 'StealthWebinar sends every webinar registration to Stealth (Registrations page) and tags the contact “stealth”. The tracking script on the thank-you page tags the visitor “registered”. Either tag means the person completed registration.' },
      { id: 'sales-source', term: 'Sales', what: 'Each sale arrives through the sales webhook and is matched to a contact by email. Refunded, failed and cancelled sales are left out of every revenue figure.' },
      { id: 'freshness', term: 'How fresh the numbers are', what: 'Each view is cached for 2–3 minutes and refreshed in the background, so new activity appears within a few minutes. Live is refreshed every 10 seconds. The very first time a long period (e.g. “All time”) is opened it can take up to a minute to calculate; after that it opens instantly.' },
      { id: 'blind-spots', term: 'What we can’t see', what: 'Visits from browsers that block scripts, and anything that happens off our pages (e.g. inside Facebook before the click). Identification times were only recorded from 24 Jul 2026, so “time to identify” covers people identified since then.' },
    ],
  },
  {
    id: 'reading', title: 'Reading the dashboard',
    entries: [
      { id: 'period', term: 'Period', what: 'The date range at the top. Days start and end at midnight in your display timezone (the clock icon at the top right). “Last 30 days” includes today.' },
      { id: 'compare', term: 'Compare', what: 'Compares the period with the one just before it, of the same length (e.g. the 30 days before the last 30 days). Cards show the change as a percentage; charts draw the previous period as a dashed line.',
        how: 'Change = (this period − previous period) ÷ previous period.',
        note: 'Green means the change is good for the business, red means bad — so a falling bounce rate or abandon count shows green.' },
      { id: 'granularity', term: 'Granularity', what: 'How charts group time: by hour, day, week (Monday to Sunday) or month. “Auto” picks hours for 1–2 days, days up to 3 months, weeks up to a year, then months.' },
      { id: 'filters', term: 'Filters', what: 'Narrow the whole dashboard to a source, medium, campaign, ad, ad set, page or site. Several values of the same filter are combined with OR (facebook OR fb); different filters are combined with AND (facebook AND this campaign).',
        note: 'A page or site filter keeps only views of those pages, and only the people who visited them in the period.' },
      { id: 'views', term: 'Saved views', what: 'Saves the current tab, period, filters and chart settings under a name everyone in the workspace can open. The address in your browser does the same — copy it to share exactly what you are looking at.' },
    ],
  },
  {
    id: 'traffic', title: 'Traffic',
    entries: [
      { id: 'page-views', term: 'Page views', what: 'Every time a tracked page loads. Reloading a page counts again.' },
      { id: 'visitors', term: 'Visitors', what: 'The number of different people (visitor IDs) who viewed at least one page in the period.', how: 'Distinct visitor IDs among the period’s page views.', note: 'See “How a visitor is recognised” — one person on two devices can count twice until they identify.' },
      { id: 'sessions', term: 'Sessions', what: 'A visit: everything one person does in one browser tab, from opening it until the tab is closed.', how: 'Distinct session IDs among the period’s page views. A session ID lives in the tab, so a tab left open for days is still one session.' },
      { id: 'new-visitors', term: 'New visitors', what: 'People seen for the very first time during the period.', how: 'Visitors whose record was created inside the period. For charts, “new” means first seen in that day / week.' },
      { id: 'returning-visitors', term: 'Returning visitors', what: 'People who visited in the period but were first seen before it — they came back.', how: 'Visitors − new visitors.' },
      { id: 'bounce-rate', term: 'Bounce rate', what: 'The share of visits where the person looked at one page and left without viewing a second tracked page.',
        how: 'Sessions with exactly one page view ÷ all sessions. On the Pages tab it is per landing page: sessions that started on that page and saw nothing else ÷ sessions that started there.',
        note: 'A high bounce rate is normal for a single-page funnel (e.g. a webinar page where the next step happens in an embedded form or on another domain we don’t track in the same tab). Compare pages with each other, or a page with itself over time, rather than against a general benchmark.' },
      { id: 'pages-per-session', term: 'Pages per session', what: 'How many pages a visit includes on average.', how: 'Page views ÷ sessions.' },
      { id: 'median-session', term: 'Median session', what: 'How long a typical multi-page visit lasts.',
        how: 'For every session with 2+ page views: time from its first to its last page view. The median (the middle value) is shown.',
        note: 'One-page visits are left out because their length can’t be measured. We use the median, not the average, because a tab left open for days would distort an average.' },
    ],
  },
  {
    id: 'leads', title: 'Leads, registrations and sales',
    entries: [
      { id: 'identified', term: 'Identified lead', what: 'A person who has given us an email address or phone number.', how: 'In a period: people whose first identification happened in that period.' },
      { id: 'identification-rate', term: 'Identification rate', what: 'How much of the traffic turns into leads.', how: 'Identified leads in the period ÷ visitors in the period.' },
      { id: 'registered', term: 'Registered', what: 'An identified lead who completed webinar registration.', how: 'Identified (email/phone) AND tagged “stealth” or “registered”.',
        note: 'The thank-you page can tag a browser that never typed an email itself (e.g. a different device). Those aren’t counted as registered leads, so registered + abandoned always adds up to identified.' },
      { id: 'registrations', term: 'Registrations (count)', what: 'Registration records received from StealthWebinar in the period.', how: 'Count of StealthWebinar webhook records by the time they arrived.',
        note: 'One person can register more than once, and someone identified last month can register this month — so this count can differ from “registered leads”.' },
      { id: 'registration-rate', term: 'Registration rate', what: 'Of the leads we identified, how many went on to register.', how: 'Registered ÷ identified (for the same group of people).' },
      { id: 'abandoned', term: 'Abandoned lead', what: 'Someone who gave us their email or phone but never completed registration.', how: 'Identified AND has neither the “stealth” nor the “registered” tag.',
        note: 'These are the people worth following up — the Leads & abandonment tab lists them, with the last page they saw, and exports them to CSV.' },
      { id: 'abandon-rate', term: 'Abandon rate', what: 'The share of identified leads who did not register.', how: 'Abandoned ÷ identified.' },
      { id: 'anonymous', term: 'Anonymous', what: 'A visitor we have no email or phone for (yet).' },
      { id: 'sales', term: 'Sales and revenue', what: 'Sales received in the period and their total value.', how: 'Sales by the time they arrived, excluding refunded, failed and cancelled. Revenue = sum of their amounts.' },
      { id: 'buyers', term: 'Buyers', what: 'People with at least one (non-refunded) sale.' },
      { id: 'purchase-rate', term: 'Purchase rate', what: 'How many registered people bought.', how: 'Buyers ÷ registered leads in the tables; on the Visitors tab, buyers ÷ visitors in each group.' },
      { id: 'revenue-per-person', term: 'Revenue per person', what: 'Lifetime revenue from a group divided by the number of people in it — a quick way to compare what a campaign’s audience is worth.' },
    ],
  },
  {
    id: 'tabs', title: 'The tabs, one by one',
    entries: [
      { id: 'journey', term: 'Journey (funnel)', what: 'Follows the people first seen in the period and shows how far they got: first visit → came back another day → identified → registered → purchased.',
        how: '“Came back another day” = page views on two or more different days since the period began. Each step shows its share of everyone (“of all”) and of the step before (“of previous”).',
        note: 'Because it follows the same people, a recent period looks weaker — they’ve had less time to come back or buy.' },
      { id: 'lead-outcomes', term: 'Lead outcomes', what: 'Every lead identified on each day / week, split into those who registered (so far) and those who abandoned.' },
      { id: 'heatmap', term: 'When it happens (heatmap)', what: 'Activity by weekday and hour, in your display timezone. Darker squares are busier; the bars underneath total each hour. Switch between page views, identifications, registrations and sales — useful for timing ads, emails and webinars.' },
      { id: 'pages', term: 'Pages', what: 'Every page that was viewed, with how people arrive, leave and convert.',
        how: 'A page is its address without the “?…” part and without “www.”, so ad-tagged links group together. Entries = sessions that started on the page. Exits = multi-page sessions that ended there. Identified / registered / abandoned / buyers = visitors to the page who are (now) in that group; ID rate = identified ÷ visitors.',
        note: 'Click a page for its trend and its flow: the page viewed just before it and just after it in the same session. “(entrance)” means the session started there; “(exit)” means it ended there.' },
      { id: 'new-vs-returning', term: 'New vs returning', what: 'Compares people first seen in the period with people who came back, on the same measures. “2.0× higher” means the returning group’s rate is double the new group’s.' },
      { id: 'frequency', term: 'Visits per visitor, days active, sessions per visitor', what: 'How engaged people were within the period: how many pages each person viewed, on how many different days, and in how many separate sessions. Percentages above the bars are the share of all visitors.' },
      { id: 'time-to-return', term: 'Time to come back', what: 'For people with two or more visits in the period: the time between their first and second page view. Gaps under 30 minutes are ignored as part of the same visit.' },
      { id: 'relationship-age', term: 'Relationship age', what: 'For returning visitors: how long it has been between the first time we ever saw them and their latest visit.' },
      { id: 'timing', term: 'Time to identify / register / purchase', what: 'For people first seen in the period: how long from their first ever page view to giving their email/phone, to registering, and to their first purchase. “Visits before buying” counts their page views up to the first sale. The headline numbers are medians.' },
      { id: 'where-abandon', term: 'Where leads abandon', what: 'The people first seen in the period, grouped by campaign, ad, device… with how many were identified, registered and abandoned. Sort by abandon rate to find where registration breaks down. Groups with fewer than 5 leads are hidden.' },
      { id: 'attribution', term: 'Attribution', what: 'Groups the people first seen in the period by where they came from, and shows what they went on to do and spend.',
        how: 'Source, medium, campaign, ad (utm_content) and ad set (utm_term) come from the link they clicked. If someone clicks a newer ad later, their record moves to the newer ad (the latest click wins). Device, operating system and browser / app come from the browser they first used.',
        note: 'The bubble chart puts size (people) against conversion; bubble size is revenue or buyers. Big, high bubbles are campaigns worth scaling; big, low ones are spending reach without converting.' },
      { id: 'cohorts', term: 'Cohorts and retention', what: 'People grouped by the week (or month) they were first seen. Each row shows the share who have since identified, registered and bought, and the retention grid shows what share came back in each later week.',
        how: 'Week 0 is the week they arrived (always 100%). +1 = the following week, and so on. Weeks start on Monday. Source and campaign filters apply; the period picker doesn’t.' },
      { id: 'report-builder', term: 'Report builder', what: 'Build your own table and chart: choose what to count (people first seen in the period, or page views), how to group it, which measures to show and the chart type. The first measure drives the chart and sort. Save it as a view or download it as CSV.' },
      { id: 'live', term: 'Live', what: 'The last 30 minutes, refreshed every 10 seconds. “Active now” = different visitors with a page view in the last 5 minutes.' },
    ],
  },
];

// One-line definitions for KPI cards (hover).
export const KPI_HELP = {
  visitors: 'Different people who viewed at least one page in the period.',
  new_visitors: 'People seen for the first time in the period.',
  returning_visitors: 'Visitors first seen before the period who came back.',
  visits: 'Every page load in the period.',
  identified: 'People who gave an email or phone for the first time in the period.',
  abandoned: 'Leads identified in the period who never registered.',
  registrations: 'Registration records received from StealthWebinar in the period.',
  sales: 'Sales received in the period (refunds excluded).',
  revenue: 'Total value of the period’s sales (refunds excluded).',
  identification_rate: 'Identified leads ÷ visitors.',
  registration_rate: 'Of the leads identified in the period, the share who registered.',
  bounce_rate: 'Visits (sessions) with only one page view ÷ all visits.',
  pages_per_session: 'Page views ÷ sessions.',
  avg_session_seconds: 'Median time from first to last page view, for visits with 2+ pages.',
};
